test_get_nb_char (__main__.TestExercice) ... FAIL
test_get_nb_words (__main__.TestExercice) ... ERROR
test_pair (__main__.TestExercice) ... ERROR
test_remove_third_char (__main__.TestExercice) ... ok
test_replace_char (__main__.TestExercice) ... FAIL

======================================================================
ERROR: test_get_nb_words (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 75, in test_get_nb_words
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
  File "test_exercice.py", line 75, in <listcomp>
    output = [exercice.get_nb_words(v[0], v[1]) for v in values]
TypeError: get_nb_words() takes 1 positional argument but 2 were given

======================================================================
ERROR: test_pair (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 15, in test_pair
    output = [exercice.is_even_len(v) for v in values]
  File "test_exercice.py", line 15, in <listcomp>
    output = [exercice.is_even_len(v) for v in values]
  File "/home/runner/work/c03_ch4_exercices-milom1/c03_ch4_exercices-milom1/exercice.py", line 7, in is_even_len
    result = true
NameError: name 'true' is not defined

======================================================================
FAIL: test_get_nb_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_get_nb_char
    "Mauvais calcul du nombre d'occurences du caractère"
AssertionError: Lists differ: [0, 0, 0] != [4, 1, 0]

First differing element 0:
0
4

- [0, 0, 0]
?  ^  ^

+ [4, 1, 0]
?  ^  ^
 : Mauvais calcul du nombre d'occurences du caractère

======================================================================
FAIL: test_replace_char (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 49, in test_replace_char
    'Erreur dans le remplacement de caractère'
AssertionError: Lists differ: ['', '', ''] != ['hey yad!', 'bbbbbb', 'a1234']

First differing element 0:
''
'hey yad!'

- ['', '', '']
+ ['hey yad!', 'bbbbbb', 'a1234'] : Erreur dans le remplacement de caractère

----------------------------------------------------------------------
Ran 5 tests in 0.001s

FAILED (failures=2, errors=2)
